repos:
# dogfood in the future?
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.34.1
  hooks:
    - id: check-github-workflows
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v6.0.0
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 25.9.0
  hooks:
    - id: black
- repo: https://github.com/PyCQA/flake8
  rev: 7.3.0
  hooks:
    - id: flake8
      additional_dependencies: ['flake8-bugbear==22.7.1']
- repo: https://github.com/PyCQA/isort
  rev: 7.0.0
  hooks:
    - id: isort
- repo: https://github.com/asottile/pyupgrade
  rev: v3.21.0
  hooks:
    - id: pyupgrade
      args: ["--py37-plus"]
