repos:
# dogfood in the future?
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.28.5
  hooks:
    - id: check-github-workflows
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v4.6.0
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks:
    - id: black
- repo: https://github.com/PyCQA/flake8
  rev: 7.1.0
  hooks:
    - id: flake8
      additional_dependencies: ['flake8-bugbear==22.7.1']
- repo: https://github.com/PyCQA/isort
  rev: 5.13.2
  hooks:
    - id: isort
- repo: https://github.com/asottile/pyupgrade
  rev: v3.16.0
  hooks:
    - id: pyupgrade
      args: ["--py37-plus"]
